In [1]:
import pandas as pd
import numpy as np

In [3]:
# Limpeiza dataframe de premier
premier = pd.read_csv('../csv/csv_raw/premier.csv')

# Exploro

In [4]:
premier.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2757 entries, 0 to 2756
Data columns (total 37 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   RL          2757 non-null   object
 1   Jugador     2757 non-null   object
 2   País        2757 non-null   object
 3   Posc        2757 non-null   object
 4   Equipo      2757 non-null   object
 5   Edad        2757 non-null   object
 6   Nacimiento  2757 non-null   object
 7   PJ          2757 non-null   object
 8   Titular     2757 non-null   object
 9   Mín         2757 non-null   object
 10  90 s        2757 non-null   object
 11  Gls.        2757 non-null   object
 12  Ass         2757 non-null   object
 13  G+A         2757 non-null   object
 14  G-TP        2757 non-null   object
 15  TP          2757 non-null   object
 16  TPint       2757 non-null   object
 17  TA          2757 non-null   object
 18  TR          2757 non-null   object
 19  xG          2756 non-null   object
 20  npxG        2756 non-null   object
 21  xAG         2756 non-null   object
 22  npxG+xAG    2756 non-null   object
 23  PrgC        2756 non-null   object
 24  PrgP        2756 non-null   object
 25  PrgR        2756 non-null   object
 26  Gls..1      2757 non-null   object
 27  Ast         2757 non-null   object
 28  G+A.1       2757 non-null   object
 29  G-TP.1      2757 non-null   object
 30  G+A-TP      2757 non-null   object
 31  xG.1        2756 non-null   object
 32  xAG.1       2756 non-null   object
 33  xG+xAG      2756 non-null   object
 34  npxG.1      2756 non-null   object
 35  npxG+xAG.1  2756 non-null   object
 36  Partidos    2757 non-null   object
dtypes: object(37)
memory usage: 797.1+ KB

In [6]:
premier.head()

,RL,Jugador,País,Posc,Equipo,Edad,Nacimiento,PJ,Titular,Mín,...,Ast,G+A.1,G-TP.1,G+A-TP,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1,Partidos
0,1,Max Aarons,eng ENG,DF,Bournemouth,23-331,2000,12,11,950,...,0.09,0.09,0.00,0.09,0.00,0.08,0.08,0.00,0.08,Partidos
1,2,Bénie Adama Traore,ci CIV,"DL,CC",Sheffield Utd,21-001,2002,6,3,325,...,0.00,0.00,0.00,0.00,0.07,0.13,0.20,0.07,0.20,Partidos
2,3,Tosin Adarabioyo,eng ENG,"DF,DL",Fulham,26-068,1997,2,0,3,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Partidos
3,4,Elijah Adebayo,eng ENG,DL,Luton Town,25-328,1998,13,4,405,...,0.00,0.44,0.44,0.44,0.31,0.06,0.37,0.31,0.37,Partidos
4,5,Simon Adingra,ci CIV,"DL,CC",Brighton,21-334,2002,12,8,756,...,0.12,0.48,0.36,0.48,0.16,0.17,0.34,0.16,0.34,Partidos

In [7]:
premier.shape

(2757, 37)

# Limpieza

In [8]:
# Ya se borro el primer nivel de columnas en el script de extraccion
# En mi columna Pais, me voy a quedar solo con el nombre del pais
premier['País'] = premier['País'].str.split(' ', expand=True)[1]

In [9]:
premier.columns

Index(['RL', 'Jugador', 'País', 'Posc', 'Equipo', 'Edad', 'Nacimiento', 'PJ',
       'Titular', 'Mín', '90 s', 'Gls.', 'Ass', 'G+A', 'G-TP', 'TP', 'TPint',
       'TA', 'TR', 'xG', 'npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP', 'PrgR',
       'Gls..1', 'Ast', 'G+A.1', 'G-TP.1', 'G+A-TP', 'xG.1', 'xAG.1', 'xG+xAG',
       'npxG.1', 'npxG+xAG.1', 'Partidos'],
      dtype='object')

In [10]:
# Elimino las columnas que no me interesan para mi estudio
premier.drop(['RL','PrgC','PrgP','PrgR','xG.1','xAG.1','xG+xAG','npxG.1','npxG+xAG.1','Partidos','90 s','TPint','npxG','npxG+xAG','Gls..1'
                     ,'Ast','G+A.1','G-TP.1','G+A-TP','G-TP','TP'], axis=1, inplace=True)

In [11]:
#Limpio la columna de edad
premier['Edad'] = premier['Edad'].str.split('-', expand=True)[0]

In [12]:
#Veo si hay algun valor nulo
premier.isnull().sum()

Jugador         0
País          103
Posc            0
Equipo          0
Edad            0
Nacimiento      0
PJ              0
Titular         0
Mín             0
Gls.            0
Ass             0
G+A             0
TA              0
TR              0
xG              1
xAG             1
dtype: int64

In [13]:
#Como veo que no tienen sentido los datos, los elimino
premier.dropna(inplace=True)
#Ya no hay nulos

In [14]:
premier['Posc'].unique()

array(['DF', 'DL,CC', 'DF,DL', 'DL', 'DF,CC', 'PO', 'CC', 'CC,DL',
       'CC,DF', 'DL,DF'], dtype=object)

In [15]:
# Filtro la columna Posc para que me queden solo cuatro grupos: Portero, Defensa, Centrocampista y Delantero
premier['Posc'] =premier['Posc'].replace({
    'DF': 'Defensa',
    'CC,DL': 'Centrocampista',
    'CC': 'Centrocampista',
    'DF,CC': 'Defensa',
    'DL,CC': 'Delantero',
    'DF,DL': 'Defensa',
    'DL': 'Delantero',
    'CC,DF': 'Centrocampista',
    'DL,DF': 'Delantero'})

In [16]:
premier['Posc'].value_counts()

Defensa           931
Centrocampista    849
Delantero         686
PO                187
Name: Posc, dtype: int64

In [17]:
premier = premier.rename(columns={'Gls': 'Goles','Ass': 'Asistencias','G+A': 'Goles+Asistencias','TA': 'Tarjetas Amarillas',
                               'TR': 'Tarjetas Rojas','xG': 'Goles Esperados','xAG':'Asistencias Esperadas'})

In [18]:
premier = premier.reset_index(drop=True)
premier

,Jugador,País,Posc,Equipo,Edad,Nacimiento,PJ,Titular,Mín,Gls.,Asistencias,Goles+Asistencias,Tarjetas Amarillas,Tarjetas Rojas,Goles Esperados,Asistencias Esperadas
0,Max Aarons,ENG,Defensa,Bournemouth,23,2000,12,11,950,0,1,1,1,0,0.0,0.8
1,Bénie Adama Traore,CIV,Delantero,Sheffield Utd,21,2002,6,3,325,0,0,0,0,0,0.3,0.5
2,Tosin Adarabioyo,ENG,Defensa,Fulham,26,1997,2,0,3,0,0,0,0,0,0.0,0.0
3,Elijah Adebayo,ENG,Delantero,Luton Town,25,1998,13,4,405,2,0,2,1,0,1.4,0.3
4,Simon Adingra,CIV,Delantero,Brighton,21,2002,12,8,756,3,1,4,2,0,1.4,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2648,Wilfried Zaha,CIV,Delantero,Crystal Palace,26,1992,38,37,3280,4,3,7,5,0,5.2,4.0
2649,Christoph Zimmermann,GER,Defensa,Norwich City,26,1993,17,16,1430,0,1,1,3,0,0.4,0.1
2650,Oleksandr Zinchenko,UKR,Defensa,Manchester City,22,1996,19,13,1276,0,0,0,2,1,0.5,1.5
2651,Richairo Živković,CUW,Delantero,Sheffield Utd,22,1996,5,0,112,0,0,0,0,0,0.1,0.1
2652,Kurt Zouma,FRA,Defensa,Chelsea,24,1994,28,25,2344,0,0,0,6,0,1.2,0.2

# Exporto a csv limpio

In [19]:
premier.to_csv('../csv/csv_limpios/premier_lp.csv')