In [1]:
import pandas as pd
import numpy as np

In [2]:
# Limpeiza dataframe de premier
premier = pd.read_csv('../csv/csv_raw/premier.csv')

# Exploro

In [3]:
premier.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3331 entries, 0 to 3330
Data columns (total 38 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   RL          3331 non-null   object
 1   Jugador     3331 non-null   object
 2   País        3331 non-null   object
 3   Posc        3331 non-null   object
 4   Equipo      3331 non-null   object
 5   Edad        3331 non-null   object
 6   Nacimiento  3331 non-null   object
 7   PJ          3331 non-null   object
 8   Titular     3331 non-null   object
 9   Mín         3331 non-null   object
 10  90 s        3331 non-null   object
 11  Gls.        3331 non-null   object
 12  Ass         3331 non-null   object
 13  G+A         3331 non-null   object
 14  G-TP        3331 non-null   object
 15  TP          3331 non-null   object
 16  TPint       3331 non-null   object
 17  TA          3331 non-null   object
 18  TR          3331 non-null   object
 19  xG          3330 non-null   object
 20  npxG        3330 non-null   object
 21  xAG         3330 non-null   object
 22  npxG+xAG    3330 non-null   object
 23  PrgC        3330 non-null   object
 24  PrgP        3330 non-null   object
 25  PrgR        3330 non-null   object
 26  Gls..1      3331 non-null   object
 27  Ast         3331 non-null   object
 28  G+A.1       3331 non-null   object
 29  G-TP.1      3331 non-null   object
 30  G+A-TP      3331 non-null   object
 31  xG.1        3329 non-null   object
 32  xAG.1       3329 non-null   object
 33  xG+xAG      3329 non-null   object
 34  npxG.1      3329 non-null   object
 35  npxG+xAG.1  3329 non-null   object
 36  Partidos    3331 non-null   object
 37  Temporada   3331 non-null   object
dtypes: object(38)
memory usage: 989.0+ KB

In [4]:
premier.head()

,RL,Jugador,País,Posc,Equipo,Edad,Nacimiento,PJ,Titular,Mín,...,G+A.1,G-TP.1,G+A-TP,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1,Partidos,Temporada
0,1,Patrick van Aanholt,nl NED,DF,Crystal Palace,26,1990,28,25,2184,...,0.25,0.21,0.25,0.13,0.09,0.21,0.13,0.21,Partidos,2017-2018
1,2,Rolando Aarons,eng ENG,"CC,DL",Newcastle Utd,21,1995,4,1,139,...,0.00,0.00,0.00,0.04,0.00,0.04,0.04,0.04,Partidos,2017-2018
2,3,Tammy Abraham,eng ENG,DL,Swansea City,19,1997,31,15,1726,...,0.31,0.26,0.31,0.35,0.08,0.44,0.35,0.44,Partidos,2017-2018
3,4,Charlie Adam,sct SCO,CC,Stoke City,31,1985,11,5,411,...,0.00,0.00,0.00,0.36,0.27,0.63,0.19,0.46,Partidos,2017-2018
4,5,Adrián,es ESP,PO,West Ham,30,1987,19,19,1710,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Partidos,2017-2018

In [5]:
premier.shape

(3331, 38)

# Limpieza

In [6]:
# Ya se borro el primer nivel de columnas en el script de extraccion
# En mi columna Pais, me voy a quedar solo con el nombre del pais
premier['País'] = premier['País'].str.split(' ', expand=True)[1]

In [7]:
premier.columns

Index(['RL', 'Jugador', 'País', 'Posc', 'Equipo', 'Edad', 'Nacimiento', 'PJ',
       'Titular', 'Mín', '90 s', 'Gls.', 'Ass', 'G+A', 'G-TP', 'TP', 'TPint',
       'TA', 'TR', 'xG', 'npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP', 'PrgR',
       'Gls..1', 'Ast', 'G+A.1', 'G-TP.1', 'G+A-TP', 'xG.1', 'xAG.1', 'xG+xAG',
       'npxG.1', 'npxG+xAG.1', 'Partidos', 'Temporada'],
      dtype='object')

In [8]:
# Elimino las columnas que no me interesan para mi estudio
premier.drop(['RL','PrgC','PrgP','PrgR','xG.1','xAG.1','xG+xAG','npxG.1','npxG+xAG.1','Partidos','90 s','TPint','npxG','npxG+xAG','Gls..1'
                     ,'Ast','G+A.1','G-TP.1','G+A-TP','G-TP','TP'], axis=1, inplace=True)

In [9]:
#Limpio la columna de edad
premier['Edad'] = premier['Edad'].str.split('-', expand=True)[0]

In [10]:
#Veo si hay algun valor nulo
premier.isnull().sum()

Jugador         0
País          125
Posc            0
Equipo          0
Edad            0
Nacimiento      0
PJ              0
Titular         0
Mín             0
Gls.            0
Ass             0
G+A             0
TA              0
TR              0
xG              1
xAG             1
Temporada       0
dtype: int64

In [11]:
#Como veo que no tienen sentido los datos, los elimino
premier.dropna(inplace=True)
#Ya no hay nulos

In [12]:
premier['Posc'].unique()

array(['DF', 'CC,DL', 'DL', 'CC', 'PO', 'DF,CC', 'DL,CC', 'DL,DF',
       'CC,DF', 'DF,DL'], dtype=object)

In [13]:
# Filtro la columna Posc para que me queden solo cuatro grupos: Portero, Defensa, Centrocampista y Delantero
premier['Posc'] =premier['Posc'].replace({
    'DF': 'Defensa',
    'CC,DL': 'Centrocampista',
    'CC': 'Centrocampista',
    'DF,CC': 'Defensa',
    'DL,CC': 'Delantero',
    'DF,DL': 'Defensa',
    'DL': 'Delantero',
    'CC,DF': 'Centrocampista',
    'DL,DF': 'Delantero'})

In [14]:
premier['Posc'].value_counts()

Defensa           1125
Centrocampista    1034
Delantero          810
PO                 236
Name: Posc, dtype: int64

In [15]:
premier = premier.rename(columns={'País':'Pais','Posc':'Posicion','Gls.': 'Goles','Ass': 'Asistencias','G+A': 'Goles+Asistencias','TA': 'Tarjetas Amarillas',
                               'TR': 'Tarjetas Rojas','xG': 'Goles Esperados','xAG':'Asistencias Esperadas'})

In [16]:
premier = premier.reset_index(drop=True)
premier

,Jugador,Pais,Posicion,Equipo,Edad,Nacimiento,PJ,Titular,Mín,Goles,Asistencias,Goles+Asistencias,Tarjetas Amarillas,Tarjetas Rojas,Goles Esperados,Asistencias Esperadas,Temporada
0,Patrick van Aanholt,NED,Defensa,Crystal Palace,26,1990,28,25,2184,5,1,6,7,0,3.1,2.1,2017-2018
1,Rolando Aarons,ENG,Centrocampista,Newcastle Utd,21,1995,4,1,139,0,0,0,0,0,0.1,0.0,2017-2018
2,Tammy Abraham,ENG,Delantero,Swansea City,19,1997,31,15,1726,5,1,6,0,0,6.8,1.6,2017-2018
3,Charlie Adam,SCO,Centrocampista,Stoke City,31,1985,11,5,411,0,0,0,2,1,1.6,1.2,2017-2018
4,Adrián,ESP,PO,West Ham,30,1987,19,19,1710,0,0,0,2,0,0.0,0.0,2017-2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3200,Jordan Zemura,ZIM,Defensa,Bournemouth,22,1999,19,17,1454,0,1,1,1,0,0.4,1.9,2022-2023
3201,Oleksandr Zinchenko,UKR,Defensa,Arsenal,25,1996,27,26,2118,1,2,3,3,0,1.4,1.4,2022-2023
3202,Hakim Ziyech,MAR,Delantero,Chelsea,29,1993,18,6,661,0,3,3,1,0,0.6,2.2,2022-2023
3203,Kurt Zouma,FRA,Defensa,West Ham,27,1994,25,24,1989,2,0,2,0,0,2.2,0.1,2022-2023
3204,Martin Ødegaard,NOR,Centrocampista,Arsenal,23,1998,37,37,3127,15,7,22,4,0,10.0,8.1,2022-2023

# Exporto a csv limpio

In [17]:
premier.to_csv('../csv/csv_limpios/premier_lp.csv')