In [1]:
import pandas as pd
import numpy as np

In [2]:
# Limpeiza dataframe de jugadores_2023
jugadores_2022 = pd.read_csv('../csv/csv_raw/jugadores_2022.csv')

## Exploro el Dataframe

In [3]:
# Exploro la tabla para ver la utilidad de sus variables
jugadores_2022.describe()

,RL,Jugador,País,Posc,Equipo,Edad,Nacimiento,PJ,Titular,Mín,...,Ast,G+A.1,G-TP.1,G+A-TP,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1,Partidos
count,619,619,617,619,619,619,619,619,619,619,...,619,619,619,619,616,616,616,616,616,619
unique,597,582,64,11,21,25,26,39,40,509,...,49,85,66,81,69,43,88,63,83,1
top,RL,Jugador,es ESP,DF,Cádiz,25,1997,1,0,Mín,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Partidos
freq,23,23,347,174,38,55,52,45,80,23,...,326,233,321,235,113,137,81,113,81,619

In [4]:
jugadores_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 619 entries, 0 to 618
Data columns (total 37 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   RL          619 non-null    object
 1   Jugador     619 non-null    object
 2   País        617 non-null    object
 3   Posc        619 non-null    object
 4   Equipo      619 non-null    object
 5   Edad        619 non-null    object
 6   Nacimiento  619 non-null    object
 7   PJ          619 non-null    object
 8   Titular     619 non-null    object
 9   Mín         619 non-null    object
 10  90 s        619 non-null    object
 11  Gls.        619 non-null    object
 12  Ass         619 non-null    object
 13  G+A         619 non-null    object
 14  G-TP        619 non-null    object
 15  TP          619 non-null    object
 16  TPint       619 non-null    object
 17  TA          619 non-null    object
 18  TR          619 non-null    object
 19  xG          616 non-null    object
 20  npxG        616 non-null    object
 21  xAG         616 non-null    object
 22  npxG+xAG    616 non-null    object
 23  PrgC        616 non-null    object
 24  PrgP        616 non-null    object
 25  PrgR        616 non-null    object
 26  Gls..1      619 non-null    object
 27  Ast         619 non-null    object
 28  G+A.1       619 non-null    object
 29  G-TP.1      619 non-null    object
 30  G+A-TP      619 non-null    object
 31  xG.1        616 non-null    object
 32  xAG.1       616 non-null    object
 33  xG+xAG      616 non-null    object
 34  npxG.1      616 non-null    object
 35  npxG+xAG.1  616 non-null    object
 36  Partidos    619 non-null    object
dtypes: object(37)
memory usage: 179.1+ KB

## Limpieza

In [5]:
jugadores_2022.head()

,RL,Jugador,País,Posc,Equipo,Edad,Nacimiento,PJ,Titular,Mín,...,Ast,G+A.1,G-TP.1,G+A-TP,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1,Partidos
0,1,Abner,br BRA,DF,Betis,22,2000,13,7,607,...,0.00,0.00,0.00,0.00,0.25,0.02,0.27,0.25,0.27,Partidos
1,2,Álvaro Aceves,es ESP,PO,Valladolid,19,2003,1,0,13,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Partidos
2,3,Marcos Acuña,ar ARG,DF,Sevilla,30,1991,30,21,1912,...,0.09,0.24,0.14,0.24,0.05,0.20,0.26,0.05,0.26,Partidos
3,4,Julen Agirrezabala,es ESP,PO,Athletic Club,21,2000,8,7,675,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Partidos
4,5,Álvaro Aguado,es ESP,CC,Valladolid,26,1996,34,18,1888,...,0.10,0.14,0.05,0.14,0.05,0.11,0.15,0.05,0.15,Partidos

In [6]:
# Ya se borro el primer nivel de columnas en el script de extraccion
# En mi columna Pais, me voy a quedar solo con el nombre del pais
jugadores_2022['País'] = jugadores_2022['País'].str.split(' ', expand=True)[1]

In [7]:
jugadores_2022.columns

Index(['RL', 'Jugador', 'País', 'Posc', 'Equipo', 'Edad', 'Nacimiento', 'PJ',
       'Titular', 'Mín', '90 s', 'Gls.', 'Ass', 'G+A', 'G-TP', 'TP', 'TPint',
       'TA', 'TR', 'xG', 'npxG', 'xAG', 'npxG+xAG', 'PrgC', 'PrgP', 'PrgR',
       'Gls..1', 'Ast', 'G+A.1', 'G-TP.1', 'G+A-TP', 'xG.1', 'xAG.1', 'xG+xAG',
       'npxG.1', 'npxG+xAG.1', 'Partidos'],
      dtype='object')

In [8]:
# Elimino las columnas que no me interesan para mi estudio
jugadores_2022.drop(['RL','PrgC','PrgP','PrgR','xG.1','xAG.1','xG+xAG','npxG.1','npxG+xAG.1','Partidos','90 s','TPint','npxG','npxG+xAG','Gls..1'
                     ,'Ast','G+A.1','G-TP.1','G+A-TP','G-TP','TP'], axis=1, inplace=True)

In [9]:
#Limpio la columna de edad
jugadores_2022['Edad'] = jugadores_2022['Edad'].str.split('-', expand=True)[0]

In [10]:
#Veo si hay algun valor nulo
jugadores_2022.isnull().sum()

Jugador        0
País          25
Posc           0
Equipo         0
Edad           0
Nacimiento     0
PJ             0
Titular        0
Mín            0
Gls.           0
Ass            0
G+A            0
TA             0
TR             0
xG             3
xAG            3
dtype: int64

In [11]:
#Veo que filas tienen pais nulo
jugadores_2022[jugadores_2022['País'].isnull()]
#Como veo que no tienen sentido los datos, los elimino
jugadores_2022.dropna(inplace=True)
#Ya no hay nulos

In [12]:
jugadores_2022['Posc'].unique()

array(['DF', 'PO', 'CC', 'DL', 'CC,DF', 'CC,DL', 'DL,CC', 'DF,CC',
       'DL,DF', 'DF,DL'], dtype=object)

In [13]:
# Filtro la columna Posc para que me queden solo cuatro grupos: Portero, Defensa, Centrocampista y Delantero
jugadores_2022['Posc'] =jugadores_2022['Posc'].replace({
    'DF': 'Defensa',
    'CC,DL': 'Centrocampista',
    'CC': 'Centrocampista',
    'DF,CC': 'Defensa',
    'DL,CC': 'Delantero',
    'DF,DL': 'Defensa',
    'DL': 'Delantero',
    'CC,DF': 'Centrocampista',
    'DL,DF': 'Delantero'})

In [14]:
jugadores_2022['Posc'].value_counts()

Defensa           201
Centrocampista    195
Delantero         153
PO                 44
Name: Posc, dtype: int64

In [15]:
jugadores_2022 = jugadores_2022.rename(columns={'Gls': 'Goles','Ass': 'Asistencias','G+A': 'Goles+Asistencias','TA': 'Tarjetas Amarillas',
                               'TR': 'Tarjetas Rojas','xG': 'Goles Esperados','xAG':'Asistencias Esperadas'})

In [16]:
#Borro los jugadores que estan dos veces
jugadores_2022 = jugadores_2022.drop_duplicates(subset='Jugador', keep='first').reset_index(drop=True)

In [17]:
jugadores_2022

,Jugador,País,Posc,Equipo,Edad,Nacimiento,PJ,Titular,Mín,Gls.,Asistencias,Goles+Asistencias,Tarjetas Amarillas,Tarjetas Rojas,Goles Esperados,Asistencias Esperadas
0,Abner,BRA,Defensa,Betis,22,2000,13,7,607,0,0,0,2,0,1.7,0.1
1,Álvaro Aceves,ESP,PO,Valladolid,19,2003,1,0,13,0,0,0,0,0,0.0,0.0
2,Marcos Acuña,ARG,Defensa,Sevilla,30,1991,30,21,1912,3,2,5,10,3,1.2,4.3
3,Julen Agirrezabala,ESP,PO,Athletic Club,21,2000,8,7,675,0,0,0,0,0,0.0,0.0
4,Álvaro Aguado,ESP,Centrocampista,Valladolid,26,1996,34,18,1888,1,2,3,4,0,1.0,2.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573,Jawad El Yamiq,MAR,Defensa,Valladolid,30,1992,25,19,1608,1,0,1,1,1,1.1,0.4
574,Joseba Zaldúa,ESP,Defensa,Cádiz,30,1992,10,7,639,0,1,1,4,0,0.0,0.0
575,Oier Zarraga,ESP,Centrocampista,Athletic Club,23,1999,26,6,852,0,0,0,5,0,1.3,1.1
576,Igor Zubeldia,ESP,Defensa,Real Sociedad,25,1997,31,29,2542,1,1,2,11,0,0.9,0.4
577,Martín Zubimendi,ESP,Centrocampista,Real Sociedad,23,1999,36,35,3101,1,3,4,12,0,1.9,2.0

# Exporto csv limpio

In [18]:
jugadores_2022.to_csv('../csv/csv_limpios/jugadores_2022_lp.csv')