In [10]:
import pandas as pd
import numpy as np

# Concateno todas las ligas

In [11]:
# Importo mis tablas de datos
premier = pd.read_csv('../csv/csv_limpios/premier_lp.csv', index_col=0)
liga = pd.read_csv('../csv/csv_limpios/laliga_lp.csv', index_col=0)
serie= pd.read_csv('../csv/csv_limpios/serie_lp.csv',   index_col=0)

In [12]:
premier

,Jugador,Pais,Posicion,Equipo,Edad,Nacimiento,PJ,Titular,Mín,Goles,Asistencias,Goles+Asistencias,Tarjetas Amarillas,Tarjetas Rojas,Goles Esperados,Asistencias Esperadas,Temporada
0,Patrick van Aanholt,NED,Defensa,Crystal Palace,26,1990,28,25,2184,5,1,6,7,0,3.1,2.1,2017-2018
1,Rolando Aarons,ENG,Centrocampista,Newcastle Utd,21,1995,4,1,139,0,0,0,0,0,0.1,0.0,2017-2018
2,Tammy Abraham,ENG,Delantero,Swansea City,19,1997,31,15,1726,5,1,6,0,0,6.8,1.6,2017-2018
3,Charlie Adam,SCO,Centrocampista,Stoke City,31,1985,11,5,411,0,0,0,2,1,1.6,1.2,2017-2018
4,Adrián,ESP,PO,West Ham,30,1987,19,19,1710,0,0,0,2,0,0.0,0.0,2017-2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3200,Jordan Zemura,ZIM,Defensa,Bournemouth,22,1999,19,17,1454,0,1,1,1,0,0.4,1.9,2022-2023
3201,Oleksandr Zinchenko,UKR,Defensa,Arsenal,25,1996,27,26,2118,1,2,3,3,0,1.4,1.4,2022-2023
3202,Hakim Ziyech,MAR,Delantero,Chelsea,29,1993,18,6,661,0,3,3,1,0,0.6,2.2,2022-2023
3203,Kurt Zouma,FRA,Defensa,West Ham,27,1994,25,24,1989,2,0,2,0,0,2.2,0.1,2022-2023
3204,Martin Ødegaard,NOR,Centrocampista,Arsenal,23,1998,37,37,3127,15,7,22,4,0,10.0,8.1,2022-2023

In [13]:
#Concateno las tablas
jugadores = pd.concat([premier, liga, serie])

# Exploro

In [14]:
jugadores.head()

,Jugador,Pais,Posicion,Equipo,Edad,Nacimiento,PJ,Titular,Mín,Goles,Asistencias,Goles+Asistencias,Tarjetas Amarillas,Tarjetas Rojas,Goles Esperados,Asistencias Esperadas,Temporada
0,Patrick van Aanholt,NED,Defensa,Crystal Palace,26,1990,28,25,2184,5,1,6,7,0,3.1,2.1,2017-2018
1,Rolando Aarons,ENG,Centrocampista,Newcastle Utd,21,1995,4,1,139,0,0,0,0,0,0.1,0.0,2017-2018
2,Tammy Abraham,ENG,Delantero,Swansea City,19,1997,31,15,1726,5,1,6,0,0,6.8,1.6,2017-2018
3,Charlie Adam,SCO,Centrocampista,Stoke City,31,1985,11,5,411,0,0,0,2,1,1.6,1.2,2017-2018
4,Adrián,ESP,PO,West Ham,30,1987,19,19,1710,0,0,0,2,0,0.0,0.0,2017-2018

In [15]:
jugadores.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10247 entries, 0 to 3570
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Jugador                10247 non-null  object
 1   Pais                   10247 non-null  object
 2   Posicion               10247 non-null  object
 3   Equipo                 10247 non-null  object
 4   Edad                   10247 non-null  int64
 5   Nacimiento             10247 non-null  int64
 6   PJ                     10247 non-null  int64
 7   Titular                10247 non-null  int64
 8   Mín                    10247 non-null  int64
 9   Goles                  10247 non-null  int64
 10  Asistencias            10247 non-null  int64
 11  Goles+Asistencias      10247 non-null  int64
 12  Tarjetas Amarillas     10247 non-null  int64
 13  Tarjetas Rojas         10247 non-null  int64
 14  Goles Esperados        10247 non-null  float64
 15  Asistencias Esperadas  10247 non-null  float64
 16  Temporada              10247 non-null  object
dtypes: float64(2), int64(10), object(5)
memory usage: 1.4+ MB

In [16]:
jugadores.shape

(10247, 17)

# Limpieza

In [17]:
# Agrupo los jugadores que se repiten y hago la media de sus valores
def custom_agg(x):
    if x.dtype == "float64" or x.dtype == "int64":
        if x.name == 'Edad':
            return np.max(x)
        else:
            return np.mean(x)
    elif x.dtype == "object":  # Asume que el tipo de objeto es una cadena
        return x.iloc[0]
    
jugadores_tot = jugadores.groupby('Jugador').agg(custom_agg)

In [18]:
jugadores_tot

,Pais,Posicion,Equipo,Edad,Nacimiento,PJ,Titular,Mín,Goles,Asistencias,Goles+Asistencias,Tarjetas Amarillas,Tarjetas Rojas,Goles Esperados,Asistencias Esperadas,Temporada
Jugador,,,,,,,,,,,,,,,,
Aaron Connolly,IRL,Delantero,Brighton,21,2000.0,15.000000,8.000000,735.000000,1.666667,0.666667,2.333333,0.000000,0.000000,2.800000,0.266667,2019-2020
Aaron Cresswell,ENG,Defensa,West Ham,32,1989.0,30.333333,29.166667,2586.000000,1.000000,2.666667,3.666667,4.000000,0.000000,0.850000,3.483333,2017-2018
Aaron Hickey,SCO,Defensa,Brentford,20,2002.0,24.333333,22.333333,1831.333333,1.666667,0.666667,2.333333,5.666667,0.333333,0.466667,0.766667,2022-2023
Aaron Lennon,ENG,Centrocampista,Burnley,34,1987.0,17.800000,11.400000,1034.600000,0.600000,0.600000,1.200000,1.800000,0.000000,0.540000,0.460000,2017-2018
Aaron Mooy,AUS,Centrocampista,Huddersfield,28,1990.0,32.000000,28.000000,2494.000000,3.000000,2.000000,5.000000,3.666667,0.333333,2.700000,3.700000,2017-2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Łukasz Teodorczyk,POL,Delantero,Udinese,28,1991.0,15.000000,1.500000,311.000000,0.500000,0.500000,1.000000,1.000000,0.000000,1.250000,0.500000,2018-2019
Šime Vrsaljko,CRO,Defensa,Atlético Madrid,29,1992.0,13.200000,9.400000,843.600000,0.200000,1.800000,2.000000,3.600000,0.000000,0.340000,0.980000,2017-2018
Žan Celar,SVN,Delantero,Roma,19,1999.0,1.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2018-2019
Žan Majer,SVN,Centrocampista,Lecce,27,1992.0,27.000000,19.000000,1664.000000,1.000000,1.000000,2.000000,7.000000,0.000000,1.800000,1.500000,2019-2020
Ștefan Radu,ROU,Defensa,Lazio,35,1986.0,21.666667,20.500000,1692.000000,0.166667,0.833333,1.000000,4.500000,0.333333,0.283333,0.716667,2017-2018

# Exporto CSV de tabla completa

In [25]:
jugadores_tot.to_csv('../csv/csv_limpios/tabla_sinvalor.csv')

# De aca a abajo falta el nuevo valor

# Agrego los valores de mercado a la tabla

In [20]:
valor = pd.read_csv('../csv/csv_limpios/valores.csv')

In [21]:
valor.value_counts()

Valor de mercado
-                   344
2,00 mill. €        155
1,00 mill. €        147
1,50 mill. €        141
3,00 mill. €        135
                   ...
26,00 mill. €         1
325 mil €             1
375 mil €             1
4,30 mill. €          1
950 mil €             1
Length: 109, dtype: int64

In [22]:
valor.head()

  Valor de mercado
0     3,50 mill. €
1     1,20 mill. €
2    30,00 mill. €
3                -
4                -

In [23]:
valor.shape

(3579, 1)

In [24]:
# Igualo el indice de valor al de jugadores
valor.set_index(jugadores_tot.index, inplace=True)

ValueError: Length mismatch: Expected 3579 rows, received array of length 3791

In [ ]:
print(jugadores_tot.index.equals(valor.index))

In [ ]:
# Le agrego la columna valor a la tabla de jugadores
jugadores_tot['Valor de mercado'] = valor['Valor de mercado']

In [ ]:
jugadores_tot['Valor de mercado'].value_counts()

In [ ]:
# Saco los valores '-' de la columna valor
jugadores_tot = jugadores_tot[jugadores_tot['Valor de mercado'] != '-']

In [ ]:
jugadores_tot

In [ ]:
# Paso los valores de la columna valor a float
def valor_mercado(value):

    value = value.replace('€', '').replace(',', '.').strip()
    parts = value.split()
    
    if len(parts) == 2:
        number, unit = parts
        if unit == 'mill.':
            return float(number) * 1e6
        elif unit == 'mil':
            return float(number) * 1e3
    else:
        return float(value)

In [ ]:
jugadores_tot['Valor de mercado'] = jugadores_tot['Valor de mercado'].apply(valor_mercado)

In [ ]:
#Reenombro la columna posicion
jugadores_tot.rename(columns={'Posc': 'Posicion'}, inplace=True)

## Normalizo los datos para poder utilizar radar char en PowerBI

In [ ]:
#Normalizo las columnas de las estadisticas de los jugadores
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# Exporto

In [ ]:
#Exporto jugadores_tot para ir escrapeando sus valores de mercado
jugadores_tot.to_csv('../csv/csv_limpios/jugadores_completo.csv')